import type { InstanceStatus } from '@prisma/client'

export interface NextActionItem {
  actionText: string
  sourceReference?: string
  priority: number
}

export interface MissingInfoItem {
  question: string
  whyItMatters: string
}

export interface DeadlineItem {
  description: string
  dueDate?: Date
  deadlineDays?: number
  fromEvent?: string
  isUncertain: boolean
  sourceReference: string
}

export interface NavigationState {
  trackInstanceId: string
  currentStageName: string
  currentStageOrder: number
  status: InstanceStatus
  nextActions: NextActionItem[]
  missingInfoFlags: MissingInfoItem[]
  deadlines: DeadlineItem[]
  uplNote: string
}

// Rendered verbatim in every NavigationState response — not generated by AI each turn.
export const UPL_BOUNDARY_NOTE =
  'STAND is not a law firm and does not provide legal advice. ' +
  'This is a navigation and document-organization tool. ' +
  'For legal representation, consult a licensed Michigan attorney or contact Michigan Legal Help.'
