import { findTemplate } from "@/lib/form-templates";
import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  const { templateId, fields }: { templateId: string; fields: Record<string, string> } = await req.json();

  const template = findTemplate(templateId);
  if (!template) {
    return new Response(JSON.stringify({ error: "Unknown template" }), { status: 400 });
  }

  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const fieldRows = template.fields
    .map((f) => {
      const val = fields[f.label] ?? "________________";
      return `
        <tr>
          <td class="label">${f.label}</td>
          <td class="value">${val || "________________"}</td>
        </tr>`;
    })
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${template.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; background: #fff; color: #1A2433; }
    .page { max-width: 720px; margin: 0 auto; padding: 32px; }
    .header { background: #0D1B2A; color: #fff; padding: 16px 24px; border-radius: 6px 6px 0 0; display: flex; justify-content: space-between; align-items: center; }
    .header-brand { color: #C9A84C; font-weight: 800; font-size: 13px; letter-spacing: .08em; }
    .header-sub { opacity: .55; font-size: 10px; margin-top: 2px; }
    .header-date { opacity: .4; font-size: 10px; }
    .body { border: 1px solid #D4DAE2; border-top: none; padding: 28px; border-radius: 0 0 6px 6px; }
    h1 { font-size: 18px; color: #0D1B2A; margin-bottom: 4px; font-weight: 800; }
    .desc { color: #5A6A7A; font-size: 12px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; }
    tr:last-child td { border-bottom: none; }
    td { padding: 8px 10px; font-size: 12px; border-bottom: 1px solid #F0F0F0; vertical-align: top; }
    td.label { font-weight: 600; color: #0D1B2A; width: 38%; }
    td.value { color: #1A2433; }
    .sig-block { margin-top: 28px; padding-top: 20px; border-top: 1px solid #D4DAE2; }
    .sig-label { font-weight: 700; font-size: 11px; color: #2C3E50; text-transform: uppercase; letter-spacing: .04em; margin-bottom: 8px; }
    .sig-line { border-bottom: 1px solid #000; min-height: 32px; font-family: Georgia, serif; font-style: italic; font-size: 16px; padding-bottom: 4px; color: #0D1B2A; }
    .sig-date { font-size: 11px; color: #5A6A7A; margin-top: 6px; }
    .disclaimer { margin-top: 20px; padding: 12px 16px; background: #F7F4EE; border-left: 3px solid #C9A84C; font-size: 11px; color: #5A6A7A; font-style: italic; line-height: 1.6; }
    .footer { margin-top: 32px; text-align: center; font-size: 10px; color: #9AA5B1; }
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style>
</head>
<body>
<div class="page">
  <div class="header">
    <div>
      <div class="header-brand">VERITAS SYSTEMS GROUP</div>
      <div class="header-sub">veritassystemsgroup.com · (269) 500-2430</div>
    </div>
    <div class="header-date">${today}</div>
  </div>
  <div class="body">
    <h1>${template.title}</h1>
    <p class="desc">${template.desc}</p>
    <table>${fieldRows}</table>
    ${template.signature ? `
    <div class="sig-block">
      <div class="sig-label">Signature</div>
      <div class="sig-line">${fields["__signature"] ?? ""}</div>
      <div class="sig-date">Date: ${today}</div>
    </div>` : ""}
    ${template.disclaimer ? `<div class="disclaimer">⚠️ ${template.disclaimer}</div>` : ""}
    <div class="disclaimer" style="margin-top:12px;">
      Veritas Systems Group LLC provides document preparation and navigation assistance only. We are not a law firm.
      Nothing in this document constitutes legal advice or creates an attorney-client relationship. Michigan UPL — MCL 600.916.
    </div>
  </div>
  <div class="footer">Generated by Veritas Navigator · ${today}</div>
</div>
<script>window.onload = () => window.print();</script>
</body>
</html>`;

  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
