/**
 * VERITAS JURISDICTION CLOCK RESTRAINT RULE (June 2026)
 *
 * All user-facing statutory deadlines MUST be sourced from this file.
 * No deadline number may be generated by model inference at runtime.
 *
 * To add a new entry: verify the day-count directly against current statute text.
 * Do not pattern-match from similar jurisdictions or estimate from training data.
 */

export interface JurisdictionClock {
  statute: string;
  responseDays: number;
  responseUnit: 'business_days' | 'calendar_days';
  extensionDays?: number;
  extensionCondition?: string;
  notes?: string;
}

// ─── Public Records / FOIA ────────────────────────────────────────────────────
// Source: directly verified against MCL 15.231 et seq. and 5 U.S.C. § 552

export const FOIA_CLOCKS = {
  michigan_state_local: {
    statute: 'MCL 15.231 et seq.',
    label: 'Michigan state or local public body',
    responseDays: 5,
    responseUnit: 'business_days',
    extensionDays: 10,
    extensionCondition:
      'Public body must provide written notice stating the specific reason for the extension.',
  },
  federal: {
    statute: '5 U.S.C. § 552',
    label: 'Federal agency',
    responseDays: 20,
    responseUnit: 'business_days',
    extensionDays: 10,
    extensionCondition:
      'Agency must show "unusual circumstances" as defined by the statute.',
  },
} as const satisfies Record<string, JurisdictionClock & { label: string }>;

export type FoiaKey = keyof typeof FOIA_CLOCKS;

// ─── Housing & Eviction — Notice to Quit ─────────────────────────────────────
// Source: MCL 554.134(1) — verified against current Michigan statute text

export const NOTICE_TO_QUIT_CLOCKS = {
  michigan_nonpayment: {
    statute: 'MCL 554.134(1)',
    responseDays: 7,
    responseUnit: 'calendar_days',
    notes:
      'Non-payment of rent. Tenant must pay or vacate within 7 days of written notice.',
  },
  michigan_holdover_monthly: {
    statute: 'MCL 554.134(1)',
    responseDays: 30,
    responseUnit: 'calendar_days',
    notes:
      'Month-to-month tenancy or holdover after lease expiration. 30-day written notice required.',
  },
} as const satisfies Record<string, JurisdictionClock>;

export type NoticeToQuitKey = keyof typeof NOTICE_TO_QUIT_CLOCKS;

// ─── Debt Collection — Validation Window ────────────────────────────────────
// Source: 15 U.S.C. § 1692g — FDCPA, verified against statute text

export const DEBT_COLLECTION_CLOCKS = {
  fdcpa_validation_window: {
    statute: '15 U.S.C. § 1692g',
    responseDays: 30,
    responseUnit: 'calendar_days',
    notes:
      'Consumer has 30 days from receipt of the initial debt validation notice to dispute the debt or request verification.',
  },
} as const satisfies Record<string, JurisdictionClock>;

// ─── Formatting helper ────────────────────────────────────────────────────────

export function formatDeadline(
  clock: JurisdictionClock & { label?: string }
): string {
  const unit =
    clock.responseUnit === 'business_days' ? 'business days' : 'calendar days';
  let text = `${clock.responseDays} ${unit} (${clock.statute})`;
  if (clock.extensionDays) {
    text += `, extendable by up to ${clock.extensionDays} additional ${unit}`;
    if (clock.extensionCondition) {
      text += ` — ${clock.extensionCondition}`;
    }
  }
  return text;
}
